#!/usr/bin/env bash
# Install nginx on your web-01 server

sudo apt update
sudo apt install nginx -y

sudo mkdir -p /var/www/aplusdev.tech/html
sudo chown -R $USER:$USER /var/www/aplusdev.tech/html
sudo chmod -R 755 /var/www/aplusdev.tech
echo "Hello World!" > /var/www/aplusdev.tech/html/index.html

echo "server {
    listen 80;
    listen [::]:80;

    root /var/www/aplusdev.tech/html;
    index index.html index.htm index.nginx-debian.html;

    server_name aplusdev.tech www.aplusdev.tech;

    location / {
        try_files \$uri \$uri/ =404;
    }
}" > /etc/nginx/sites-available/aplusdev.tech

sudo ln -s /etc/nginx/sites-available/aplusdev.tech /etc/nginx/sites-enabled/
sudo rm /etc/nginx/sites-enabled/default
sudo sed -i 's/# server_names_hash_bucket_size 64;/server_names_hash_bucket_size 64;/' /etc/nginx/nginx.conf

sudo service nginx restart
