#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt update
sudo apt install haproxy -y
sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver server1 54.146.86.128:80 check\n\tserver server2 100.26.152.40:80 check\n" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
