#!/usr/bin/env bash
#_____________________________________________________
#
# Bash script that displays a list of currently running processes
#+ ---------------------------------------------------
ps -faux
