#!/usr/bin/env bash

# shellcheck disable=SC2009
#____________________
#
# Bash script that displays lines containing the bash word
#+ --------------------------------------------------------
ps -u | grep 'bash'
