#!/usr/bin/env bash
#_______________________
#
# Bash script that displays the PID, along with the process name,
#+ of processes whose name contain the word bash
#+ --------------------------------------------
pgrep -l 'bash' 
