#!/usr/bin/env bash 
# _______________________
#
# Bash script that stops 4-to_infinity_and_beyond process.
#+ ------------------------------------------------------
pkill -f "4-to_infinity_and_beyond"
