#!/usr/bin/env bash
#____________________________________________________________________#
#  Bash script that displays:
#+ The content of the current directory
#+ Where only the part of the name after the first dash is displayed
#____________________________________________________________________#
for file in *
do
	echo "$file" | cut -d '-' -f 2
done
